---
# role: ansible-role-ca
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ca-arch
    image: "jomrr/molecule-archlinux:latest"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-centos7
    image: "jomrr/molecule-centos:7"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-centos8
    image: "jomrr/molecule-centos:8"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-debian9
    image: "jomrr/molecule-debian:9"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-debian10
    image: "jomrr/molecule-debian:10"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-opensuse15
    image: "jomrr/molecule-opensuse:15"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-tumbleweed
    image: "jomrr/molecule-opensuse:tumbleweed"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-ubuntu1804
    image: "jomrr/molecule-ubuntu:18.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ca-ubuntu2004
    image: "jomrr/molecule-ubuntu:20.04"
    override_command: False
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        ca_country: 'DE'
        ca_state: 'Bayern'
        ca_locality: 'Erlangen'
        ca_organization: 'Homebase'
        ca_organizational_unit: 'Homebase Certificate Authority'
        ca_name: 'Homebase'
        ca_dir: 'home'
        ca_base_url: 'http://pki.yourdomain.tld'
        ca_certs:
          component:
          client:
            - cn: 'My Mobile'
            - cn: 'My Tablet'
          mskdc:
            - cn: 'dc.yourdomain.tld'
              san:
                - 'DNS = dc'
                - 'DNS = ad.yourdomain.tld'
                - 'IP = 192.168.10.10'
                - 'otherName = 1.3.6.1.5.2.2;UTF8:dc.yourdomain.tld'
                - 'otherName = 1.3.6.1.4.1.311.25.1;FORMAT:HEX,OCTETSTRING:2BEA00D953125447A22BCF28508DFED3'
          server:
            - cn: 'server.yourdomain.tld'
              san:
                - 'DNS = server.yourdomain.tld'
                - 'DNS = mail.yourdomain.tld'
                - 'IP = 192.168.10.11'
          timestamp:
            - cn: 'My Software Timestamp'
          ocsp:
            - cn: 'My OCSP Signature'
          identity:
            email:
              - cn: 'Jonas Mauer (Mail)'
                email: 'jonas@yourdomain.tld'
                san:
                  - 'email:move'
                  - 'email:jam@yourdomain.tld'
                protect_key: True
            identity:
              - cn: 'Jonas Mauer (ID)'
                email: 'jonas@yourdomain.tld'
                san:
                  - 'email:move'
                  - 'otherName:1.3.6.1.4.1.311.20.2.3;UTF8:jonas@dc.yourdomain.tld'
                protect_key: True
          software:
            codesign:
              - cn: 'My Software'
                protect_key: True
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
