---
# file: .travis.yml

language: python

python:
  - "3.6"
  - "3.8"

services: docker

env:
  matrix:
    - MOLECULE_DIST: 'jomrr/molecule-archlinux:latest'
    - MOLECULE_DIST: 'jomrr/molecule-centos:7'
    - MOLECULE_DIST: 'jomrr/molecule-centos:8'
    - MOLECULE_DIST: 'jomrr/molecule-debian:9'
    - MOLECULE_DIST: 'jomrr/molecule-debian:10'
    - MOLECULE_DIST: 'jomrr/molecule-opensuse:15'
    - MOLECULE_DIST: 'jomrr/molecule-opensuse:tumbleweed'
    - MOLECULE_DIST: 'jomrr/molecule-ubuntu:18.04'
    - MOLECULE_DIST: 'jomrr/molecule-ubuntu:20.04'

install:
  - pip install ansible-lint docker flake8 molecule testinfra yamllint

script:
  - molecule --version
  - ansible --version
  - molecule test
