---
# role: ansible-role-ca
# file: tasks/authority.yml

- name: "CA | Manage authority {{ ca_authority.name }}"
  vars:
    __ca_authority: "{{ ca_authority }}"
    __ca_authority_parent: "{{ ca_authority.parent }}"
    __ca_authorities_by_name: "{{ ca_authorities | ca_authority_map }}"
  block:
    - name: "CA | Manage root authority material for {{ ca_authority.name }}"
      ca_root:
        base_dir: "{{ ca_base_dir }}"
        name: "{{ ca_authority.name }}"
        key_passphrase: "{{ ca_authority.key_passphrase }}"
        common_name: "{{ __ca_authority.common_name }}"
        subject: "{{ ca_subject | combine(__ca_authority.subject | default({})) }}"
        aia_base_url: "{{ (ca_aia.enabled | bool) | ternary(ca_aia.url, '') }}"
        cdp_base_url: "{{ (ca_cdp.enabled | bool) | ternary(ca_cdp.url, '') }}"
        days: "{{ __ca_authority.days }}"
        owner: "{{ ca_owner }}"
        group: "{{ ca_group }}"
        force: "{{ ca_force_reissue | bool }}"
      when: __ca_authority_parent == ca_authority.name
      no_log: true

    - name: "CA | Manage issuing authority material for {{ ca_authority.name }}"
      ca_issuing:
        base_dir: "{{ ca_base_dir }}"
        name: "{{ ca_authority.name }}"
        parent: "{{ __ca_authority_parent }}"
        key_passphrase: "{{ ca_authority.key_passphrase }}"
        parent_key_passphrase: "{{ __ca_authorities_by_name[__ca_authority_parent].key_passphrase }}"
        common_name: "{{ __ca_authority.common_name }}"
        subject: "{{ ca_subject | combine(__ca_authority.subject | default({})) }}"
        aia_base_url: "{{ (ca_aia.enabled | bool) | ternary(ca_aia.url, '') }}"
        cdp_base_url: "{{ (ca_cdp.enabled | bool) | ternary(ca_cdp.url, '') }}"
        days: "{{ __ca_authority.days }}"
        owner: "{{ ca_owner }}"
        group: "{{ ca_group }}"
        force: "{{ ca_force_reissue | bool }}"
      when: __ca_authority_parent != ca_authority.name
      no_log: true

    - name: "CA | Manage authority chain for {{ ca_authority.name }}"
      x509_chain:
        base_dir: "{{ ca_base_dir }}"
        name: "{{ ca_authority.name }}"
        parent: "{{ __ca_authority_parent }}"
        owner: "{{ ca_owner }}"
        group: "{{ ca_group }}"
        force: "{{ ca_force_reissue | bool }}"
