---
# role: ansible-role-ca
# file: tasks/authorities.yml

- name: "CA | Manage authority"
  ansible.builtin.include_tasks: authority.yml
  loop: "{{ ca_authorities }}"
  loop_control:
    loop_var: ca_authority
    label: "{{ ca_authority.name }}"
