---
# role: ca
# file: tasks/certificates.yml

- name: "CA | Manage certificate material"
  ca_certificate_batch:
    base_dir: "{{ ca_base_dir }}"
    base_url: "{{ ca_base_url }}"
    ca_name: "{{ ca_name }}"
    certificates: "{{ ca_certificates }}"
    certificate_types: "{{ ca_certificate_types }}"
    authorities: "{{ ca_authorities }}"
    kerberos_realm: "{{ ca_kerberos_realm }}"
    subject: "{{ ca_subject }}"
    renewal: "{{ ca_renewal }}"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    force: "{{ ca_force_reissue | bool }}"
  register: __ca_certificate_material_status
  no_log: true

- name: "CA | Deploy FritzBox certificates"
  ca_fritzbox_deploy:
    base_dir: "{{ ca_base_dir }}"
    certificate: "{{ ca_certificate }}"
    deploy: "{{ ca_certificate.fritzbox_deploy | default({}) }}"
    name: "{{ ca_certificate.name }}"
    force: "{{ ca_force_reissue | bool }}"
  loop: "{{ ca_certificates }}"
  loop_control:
    loop_var: ca_certificate
    label: "{{ ca_certificate.name }}"
  when:
    - >-
      ca_certificate.type == 'fritzbox'
      or 'fritzbox' in (ca_certificate.formats | default([]))
    - ca_certificate.fritzbox_deploy.enabled | default(false) | bool
  no_log: true
