---
# role: ansible-role-ca
# file: tasks/crl.yml

- name: "CA | Manage CRLs for {{ ca_authority.name }}"
  ca_crl:
    base_dir: "{{ ca_base_dir }}"
    base_url: "{{ ca_base_url }}"
    ca_name: "{{ ca_name }}"
    name: "{{ ca_authority.name }}"
    key_passphrase: "{{ ca_authority.key_passphrase }}"
    common_name: "{{ ca_authority.common_name }}"
    subject: "{{ ca_subject | combine(ca_authority.subject | default({})) }}"
    next_update_days: "{{ ca_authority.crl_days }}"
    revoked_certificates: "{{ ca_revocations.get(ca_authority.name, []) }}"
    digest: "{{ ca_authority.crl_digest | default(omit) }}"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    force: "{{ ca_force_reissue | bool }}"
  no_log: true
