---
# role: ansible-role-ca
# file: tasks/crl.yml

- name: "CA | Manage CRLs for {{ ca_authority.name }}"
  ca_crl:
    base_dir: "{{ ca_base_dir }}"
    name: "{{ ca_authority.name }}"
    format: "{{ item }}"
    key_passphrase: "{{ ca_authority.key_passphrase }}"
    common_name: "{{ ca_authority.common_name }}"
    subject: "{{ ca_subject | combine(ca_authority.subject | default({})) }}"
    next_update_days: "{{ ca_authority.crl_days }}"
    revoked_certificates: "{{ ca_authority.revocations | default([]) }}"
    digest: "{{ ca_authority.crl_digest | default(ca_default_md) }}"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    force: "{{ ca_force_reissue | bool }}"
  loop:
    - pem
    - der
  no_log: true
