---
# role: ansible-role-ca
# file: tasks/init.yml

- name: "CA | Create base directories"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    mode: "{{ item.mode }}"
  loop: "{{ ca_base_directories }}"
  loop_control:
    label: "{{ item.path }}"
  tags: init-dirs

- name: "CA | Store CA private key passphrase files"
  ansible.builtin.copy:
    content: "{{ ca_authority.key_passphrase }}\n"
    dest: "{{ ca_base_dir }}/private/{{ ca_authority.name }}-ca.pass"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    mode: "0600"
  loop: "{{ ca_authorities }}"
  loop_control:
    loop_var: ca_authority
    label: "{{ ca_authority.name }}"
  no_log: "{{ ca_no_log | bool }}"
  tags: init-passphrases
