---
# role: ansible-role-ca
# file: tasks/main.yml

- name: "CA | Load platform variables"
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"
  tags: always

- name: "CA | Assert role configuration"
  ansible.builtin.import_tasks: assert.yml
  tags: assert

- name: "CA | Install required packages"
  ansible.builtin.package:
    name: "{{ ca_packages }}"
    state: present
  tags: install

- name: "CA | Initialize filesystem layout"
  ansible.builtin.import_tasks: init.yml
  tags: init

- name: "CA | Manage CA authorities"
  ansible.builtin.import_tasks: authorities.yml
  tags: authorities

- name: "CA | Manage certificates"
  ansible.builtin.import_tasks: certificates.yml
  when: ca_certificates | length > 0
  tags: create

- name: "CA | Manage CRLs"
  ansible.builtin.import_tasks: crls.yml
  tags: crl

- name: "CA | Publish AIA and CDP artifacts"
  ansible.builtin.include_tasks: publish.yml
  when: ca_publish_targets | length > 0
  tags: publish
