---
# role: ca
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 12
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.posix.profile_tasks,ansible.posix.timer"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
  inventory:
    group_vars:
      all:
        ca_no_log: false
        ca_name: "Example"
        ca_base_url: "http://pki.molecule.test"
        ca_authorities:
          - name: "root"
            common_name: "Example Root CA"
            parent: "root"
            days: 3652
            default_days: 397
            crl_days: 30
            key_passphrase: "molecule-root-passphrase"
            revocations: []
          - name: "component"
            common_name: "Example Component CA"
            parent: "root"
            days: 1826
            default_days: 397
            crl_days: 30
            key_passphrase: "molecule-component-passphrase"
            revocations: []
          - name: "network"
            common_name: "Example Network CA"
            parent: "root"
            days: 1826
            default_days: 397
            crl_days: 30
            key_passphrase: "molecule-network-passphrase"
            revocations: []
          - name: "identity"
            common_name: "Example Identity CA"
            parent: "root"
            days: 1826
            default_days: 730
            crl_days: 30
            key_passphrase: "molecule-identity-passphrase"
            revocations: []
        ca_certificates:
          - name: "web01"
            type: "tls_server"
            common_name: "web01.molecule.test"
            san:
              - "DNS:web01.molecule.test"
              - "DNS:web01"
          - name: "client01"
            type: "tls_client"
            common_name: "client01.molecule.test"
          - name: "dc01"
            type: "mskdc"
            common_name: "dc01.molecule.test"
            krb5_realm: "MOLECULE.TEST"
            ad_object_guid: "d900ea2b-1253-4754-a22b-cf28508dfed3"
            san:
              - "DNS:dc01.molecule.test"
              - "DNS:dc01"
          - name: "fritzbox01"
            type: "fritzbox"
            common_name: "fritzbox.molecule.test"
            san:
              - "DNS:fritzbox.molecule.test"
              - "IP:192.0.2.1"
          - name: "user-full"
            type: "identity_full"
            common_name: "Molecule User Full"
            email: "user-full@molecule.test"
            san:
              - "email:user-full@molecule.test"
              - "otherName:1.3.6.1.4.1.311.20.2.3;UTF8:user-full@molecule.test"
            pfx_passphrase: "molecule-pfx-passphrase"
          - name: "user-smime"
            type: "identity"
            common_name: "Molecule User S/MIME"
            email: "user-smime@molecule.test"
            san:
              - "email:user-smime@molecule.test"
              - "otherName:1.3.6.1.4.1.311.20.2.3;UTF8:user-smime@molecule.test"
          - name: "wifi-user"
            type: "eap_tls_client"
            common_name: "wifi-user@molecule.test"
            san:
              - "email:wifi-user@molecule.test"
verifier:
  name: "ansible"
scenario:
  name: "dev"
platforms:
  - name: almalinux-latest-ca
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: debian-latest-ca
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: fedora-latest-ca
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-leap-latest-ca
    image: "docker.io/jomrr/molecule-opensuse-leap:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: opensuse-tumbleweed-latest-ca
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: true
  - name: ubuntu-latest-ca
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: true
