# role: jomrr.ca
# file: molecule/resources/playbooks/converge.yml

- name: "PLAYBOOK | Converge | ca"
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
