---
# role: ca
# file: molecule/resources/playbooks/verify.yml

- name: "Molecule | verify | ca"
  hosts: all
  gather_facts: true
  vars:
    ca_molecule_base: "{{ (ansible_facts.os_family == 'RedHat') | ternary('/etc/pki', '/etc/ssl') }}/{{ ca_name | lower }}"
  tasks:
    - name: "CA | Load role certificate type vars"
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../../vars/main.yml"

    - name: "CA | Verify generated CA artifacts"
      ca_verify:
        ca_name: "{{ ca_name }}"
        base_dir: "{{ ca_molecule_base }}"
        publish_root: /var/www/pki
        authorities: "{{ ca_authorities }}"
        certificates: "{{ ca_certificates }}"
        certificate_types: "{{ ca_certificate_types }}"
        revocations: "{{ ca_revocations }}"
        renewal: "{{ ca_renewal }}"
